### ISSUE TITLE
ACT as a Conditional VAE

### ISSUE THREAD

**Issue by WaseemDR** [yay-robot/yay_robot#2]
Impressive work thanks for sharing!

In the published paper, it seems you are not using the C-VAE encoder in the architecture anymore but in the code, it seems it is still being used exactly as in the original ACT paper. Which is the correct?
In general, the C-VAE encoder seems to be beneficial when there is one task being learned but is it still useful and valid when task-variation / multi-task is introduced?

Thanks

**Comment by lucys0** [comment]
Hi, thank you!

We are using the C-VAE encoder as in ACT. Regarding the benefit of the encoder - it's a bit unclear, but more results might come out soon. If you run ablations later, I'd be curious to hear your results!
